- hosts: 192.168.44.70
  become: yes
  become_user: root
  tasks:
    - name: Install MySQL
      apt: name={{ item }} state=latest
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Enable the MySQL service
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Remove the test database
      mysql_db: name=test state=absent