- hosts: 192.168.44.70
  become: yes
  become_user: root
  tasks:
    - name: Install MySQL
      apt: name={{ item }} state=latest
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Restart MySQL
      service: name=mysql state=restarted

    - name: Remove the test database
      mysql_db: name=test state=absent