- hosts: 192.168.44.70
  become: yes
  become_user: root
  tasks:
    - name: Install MySQL
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server-core
        - mysql-client-core
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Start the MySQL service
      action: service name=mysql state=started

    - name: Remove the test database
      mysql_db: name=test state=absent