- hosts: 192.168.180.172
  become: yes
  become_user: root
  roles:
      - { role: geerlingguy.apache }
      - { role: dj-wasabi.zabbix-server, zabbix_server_database: mysql, zabbix_server_database_long: mysql, zabbix_server_dbport: 3306 }
      - { role: dj-wasabi.zabbix-web, zabbix_server_database: mysql, zabbix_server_database_long: mysql, zabbix_server_dbport: 3306}